# Generated by Django 5.2.7 on 2025-11-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('private', models.BooleanField()),
                ('members', models.IntegerField()),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
